[[main]]
  name = "블로그"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "프로젝트"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "소개"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/KimJunDDo"
  weight = 40